backend:
    name: test-repo
    repo: open-sgf/opensgf.org
    branch: dev
local_backend: true
media_folder: "public/images"
public_folder: "/images"
site_url: https://opensgf.org
logo_url: images/open-sgf-logo.svg
collections:
    - name: "home"
      label: "Home"
      delete: false
      files:
          - name: 'ImageText Block'
            label: 'imageTextBlock'
            file: 'content/home.md'
            fields:
                - label: "Title"
                  name: "title"
                  widget: "string"
                  required: true
                - label: "Body"
                  name: "body"
                  widget: "markdown"
                  required: true
